services:
  localstack:
    container_name: localstack
    image: localstack/localstack-pro  # required for Pro
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (Pro)
    environment:
      # Activate LocalStack for AWS: https://docs.localstack.cloud/getting-started/auth-token/
      - LOCALSTACK_AUTH_TOKEN=ls-ZofecEzU-kife-4002-7879-LOGowEqie98c  # required for Pro
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"